
    create table accounts (
        id integer generated by default as identity,
        data_creazione timestamp(6) not null,
        ruolo varchar(20) not null check ((ruolo in ('ADMIN','USER'))),
        email varchar(100) not null unique,
        username varchar(100) not null unique,
        password varchar(255) not null,
        primary key (id)
    );

    create table anagrafiche (
        id integer generated by default as identity,
        id_account integer not null,
        predefinito boolean not null,
        cap varchar(100) not null,
        citta varchar(100) not null,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        provincia varchar(100) not null,
        stato varchar(100) not null,
        via varchar(100) not null,
        primary key (id)
    );

    create table autori (
        data_nascita date not null,
        id integer generated by default as identity,
        cognome varchar(255) not null,
        descrizione varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table carrelli (
        id integer generated by default as identity,
        id_account integer unique,
        primary key (id)
    );

    create table case_editrici (
        id integer generated by default as identity,
        indirizzo varchar(100) not null,
        nome varchar(100) not null,
        descrizione varchar(255) not null,
        email varchar(255) not null,
        primary key (id)
    );

    create table fatture (
        costo_spedizione numeric(10,2),
        data_emissione date not null,
        id integer generated by default as identity,
        id_ordine integer,
        totale numeric(10,2) not null,
        cliente_cap varchar(10),
        stato_fattura varchar(20) not null,
        cliente_citta varchar(100),
        cliente_cognome varchar(100) not null,
        cliente_email varchar(100) not null,
        cliente_nome varchar(100) not null,
        cliente_provincia varchar(100),
        cliente_stato varchar(100),
        numero_fattura varchar(100) not null unique,
        tipo_pagamento varchar(100) not null,
        tipo_spedizione varchar(100),
        cliente_indirizzo varchar(255),
        note TEXT,
        primary key (id)
    );

    create table generi (
        id integer generated by default as identity,
        descrizione varchar(255) not null,
        primary key (id)
    );

    create table manga (
        data_pubblicazione date not null,
        id_casa_editrice integer not null,
        id_saga integer,
        numero_copie integer not null,
        prezzo numeric(38,2) not null,
        saga_volume integer,
        immagine varchar(255),
        isbn varchar(255) not null,
        titolo varchar(255) not null,
        primary key (isbn)
    );

    create table manga_autori (
        id_autore integer not null,
        isbn_manga varchar(255) not null,
        primary key (id_autore, isbn_manga)
    );

    create table manga_generi (
        id_genere integer not null,
        isbn_manga varchar(255) not null,
        primary key (id_genere, isbn_manga)
    );

    create table ordini (
        data date not null,
        id integer generated by default as identity,
        id_account integer not null,
        id_anagrafica integer not null,
        id_stato integer not null,
        id_tipo_pagamento integer not null,
        id_tipo_spedizione integer not null,
        primary key (id)
    );

    create table righe_carrello (
        id integer generated by default as identity,
        id_carrello integer not null,
        numero_copie integer,
        isbn_manga varchar(255) not null,
        primary key (id)
    );

    create table righe_fattura (
        id integer generated by default as identity,
        id_fattura integer not null,
        numero_copie integer not null,
        prezzo_unitario numeric(10,2) not null,
        totale_riga numeric(10,2) not null,
        isbn varchar(255),
        titolo varchar(255) not null,
        primary key (id)
    );

    create table righe_ordine (
        id integer generated by default as identity,
        id_ordine integer not null,
        numero_copie integer not null,
        prezzo numeric(38,2),
        isbn_manga varchar(255) not null,
        primary key (id)
    );

    create table saghe (
        id integer generated by default as identity,
        proxy boolean not null,
        descrizione varchar(255) not null,
        immagine varchar(255),
        nome varchar(255) not null,
        primary key (id)
    );

    create table stati_ordine (
        id integer generated by default as identity,
        stato_ordine varchar(255) not null,
        primary key (id)
    );

    create table system_messages (
        code varchar(255) not null,
        messaggio varchar(255),
        primary key (code)
    );

    create table tipi_pagamento (
        id integer generated by default as identity,
        tipo_pagamento varchar(100) not null,
        primary key (id)
    );

    create table tipi_spedizione (
        costo_spedizione numeric(10,2),
        id integer generated by default as identity,
        tipo_spedizione varchar(100) not null unique,
        primary key (id)
    );

    alter table if exists anagrafiche 
       add constraint FKppcbv6im3teug10ygcq2nw6h4 
       foreign key (id_account) 
       references accounts;

    alter table if exists carrelli 
       add constraint FK8bwmqjwt5v85bcicyrb2cp03y 
       foreign key (id_account) 
       references accounts;

    alter table if exists fatture 
       add constraint FK1yam3fnrr4nuexay4p8i9e928 
       foreign key (id_ordine) 
       references ordini;

    alter table if exists manga 
       add constraint FKk0v2gv11etiuocmnsp8rkm1lb 
       foreign key (id_casa_editrice) 
       references case_editrici;

    alter table if exists manga 
       add constraint FKpj9g3xx3pcil600o1gpwwsh4h 
       foreign key (id_saga) 
       references saghe;

    alter table if exists manga_autori 
       add constraint FK8sm8r52ml93185a8y5aqcusyg 
       foreign key (id_autore) 
       references autori;

    alter table if exists manga_autori 
       add constraint FKbrfhd0saru9t2rikafxn8y2lh 
       foreign key (isbn_manga) 
       references manga;

    alter table if exists manga_generi 
       add constraint FK6nu1inap7k0aerp8gaq7aojh6 
       foreign key (id_genere) 
       references generi;

    alter table if exists manga_generi 
       add constraint FKlwtko0bh46dyuukj5g5d6f27l 
       foreign key (isbn_manga) 
       references manga;

    alter table if exists ordini 
       add constraint FKeahnhannuwy5mebvhxy8lqe8b 
       foreign key (id_account) 
       references accounts;

    alter table if exists ordini 
       add constraint FKnvr4b33empa4luxi45jqindcn 
       foreign key (id_anagrafica) 
       references anagrafiche;

    alter table if exists ordini 
       add constraint FKo9jvgplgfwdyw1w66gxj8i3iq 
       foreign key (id_stato) 
       references stati_ordine;

    alter table if exists ordini 
       add constraint FK6j0iarcfjdeljghsl5hu41ywk 
       foreign key (id_tipo_pagamento) 
       references tipi_pagamento;

    alter table if exists ordini 
       add constraint FKf7s1k810ss61tb8h9yan3kiax 
       foreign key (id_tipo_spedizione) 
       references tipi_spedizione;

    alter table if exists righe_carrello 
       add constraint FKbkny6hvx39y1qpv8knmm4p1m6 
       foreign key (id_carrello) 
       references carrelli;

    alter table if exists righe_carrello 
       add constraint FK647fphayoh41pfui4qmym6mnv 
       foreign key (isbn_manga) 
       references manga;

    alter table if exists righe_fattura 
       add constraint FKsnxaxq3vxgxbf9tb0bp7ucocv 
       foreign key (id_fattura) 
       references fatture;

    alter table if exists righe_ordine 
       add constraint FKqylepa0isnmlaqhnny012eydn 
       foreign key (isbn_manga) 
       references manga;

    alter table if exists righe_ordine 
       add constraint FK2ybnsnkyw4w9tfkxeojq1lr6h 
       foreign key (id_ordine) 
       references ordini;
