
    create table accounts (
        id integer generated by default as identity,
        email varchar(100) not null unique,
        username varchar(100) not null unique,
        ruolo varchar(255) not null,
        primary key (id)
    );

    create table anagrafiche (
        cap integer not null,
        id integer generated by default as identity,
        id_anagrafica integer,
        predefinito boolean not null,
        citta varchar(100) not null,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        provincia varchar(100) not null,
        stato varchar(100) not null,
        via varchar(100) not null,
        primary key (id)
    );

    create table autori (
        data_nascita date not null,
        id integer generated by default as identity,
        cognome varchar(255) not null,
        descrizione varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table carrelli (
        id integer generated by default as identity,
        id_account integer unique,
        primary key (id)
    );

    create table case_editrici (
        id integer generated by default as identity,
        indirizzo varchar(100) not null,
        nome varchar(100) not null,
        descrizione varchar(255) not null,
        email varchar(255) not null,
        primary key (id)
    );

    create table generi (
        id integer generated by default as identity,
        descrizione varchar(255) not null,
        primary key (id)
    );

    create table manga (
        data_pubblicazione date not null,
        id_casa_editrice integer not null,
        numero_copie integer not null,
        prezzo float(53) not null,
        immagine varchar(255) not null,
        isbn varchar(255) not null,
        titolo varchar(255) not null,
        primary key (isbn)
    );

    create table manga_autori (
        id_autore integer not null,
        isbn_manga varchar(255) not null
    );

    create table manga_generi (
        id_genere integer not null,
        isbn_manga varchar(255) not null
    );

    create table ordini (
        data date not null,
        id integer generated by default as identity,
        id_account integer,
        id_pagamento integer,
        id_spedizione integer,
        id_stato integer,
        primary key (id)
    );

    create table pagamenti (
        id integer generated by default as identity,
        tipo_pagamento varchar(100) not null,
        primary key (id)
    );

    create table righeordine (
        id integer generated by default as identity,
        id_ordine integer not null,
        numero_copie integer not null,
        id_manga varchar(255) not null,
        primary key (id)
    );

    create table spedizioni (
        id integer generated by default as identity,
        tipo_spedizione varchar(100) not null,
        primary key (id)
    );

    create table stati_ordine (
        id integer generated by default as identity,
        stato_ordine varchar(255) not null,
        primary key (id)
    );

    create table system_messages (
        code varchar(255) not null,
        messaggio varchar(255),
        primary key (code)
    );

    alter table if exists anagrafiche 
       add constraint FKoc2ya8cyewupshbwv2fuwqutx 
       foreign key (id_anagrafica) 
       references accounts;

    alter table if exists carrelli 
       add constraint FK8bwmqjwt5v85bcicyrb2cp03y 
       foreign key (id_account) 
       references accounts;

    alter table if exists manga 
       add constraint FKk0v2gv11etiuocmnsp8rkm1lb 
       foreign key (id_casa_editrice) 
       references case_editrici;

    alter table if exists manga_autori 
       add constraint FK8sm8r52ml93185a8y5aqcusyg 
       foreign key (id_autore) 
       references autori;

    alter table if exists manga_autori 
       add constraint FKbrfhd0saru9t2rikafxn8y2lh 
       foreign key (isbn_manga) 
       references manga;

    alter table if exists manga_generi 
       add constraint FK6nu1inap7k0aerp8gaq7aojh6 
       foreign key (id_genere) 
       references generi;

    alter table if exists manga_generi 
       add constraint FKlwtko0bh46dyuukj5g5d6f27l 
       foreign key (isbn_manga) 
       references manga;

    alter table if exists ordini 
       add constraint FKeahnhannuwy5mebvhxy8lqe8b 
       foreign key (id_account) 
       references accounts;

    alter table if exists ordini 
       add constraint FK76mc7hr7sthilhjy1rerhshmg 
       foreign key (id_pagamento) 
       references pagamenti;

    alter table if exists ordini 
       add constraint FKgp5h6gfg8c52s54gtsoyc2894 
       foreign key (id_spedizione) 
       references spedizioni;

    alter table if exists ordini 
       add constraint FKo9jvgplgfwdyw1w66gxj8i3iq 
       foreign key (id_stato) 
       references stati_ordine;

    alter table if exists righeordine 
       add constraint FKqofnxqjgpy7und7xfak25es7v 
       foreign key (id_manga) 
       references manga;

    alter table if exists righeordine 
       add constraint FKa30cbtoatkcx6verd9yoyguse 
       foreign key (id_ordine) 
       references ordini;
